/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package no1;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author katy
 */
public class presionart extends javax.swing.JFrame {

    /**
     * Creates new form presionart
     */
    public presionart() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        b2 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt3 = new javax.swing.JTextArea();
        b3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Vijaya", 0, 18)); // NOI18N
        jLabel1.setText("Numero inferior");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 160, 190, 61);

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });
        getContentPane().add(txt1);
        txt1.setBounds(250, 80, 110, 50);

        jLabel2.setFont(new java.awt.Font("Vijaya", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 0, 0));
        jLabel2.setText("PRUEBA DE PRESION ARTERIAL");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 0, 540, 61);

        jLabel3.setFont(new java.awt.Font("Vijaya", 0, 18)); // NOI18N
        jLabel3.setText("Numero superior");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 80, 190, 61);

        txt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt2ActionPerformed(evt);
            }
        });
        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt2KeyTyped(evt);
            }
        });
        getContentPane().add(txt2);
        txt2.setBounds(250, 160, 110, 50);

        b2.setText("CONSULTAR");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(60, 240, 240, 50);

        jButton2.setText("LIMPIAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(340, 240, 240, 50);

        jButton1.setText("Checa tus niveles de Glucosa");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 90, 240, 40);

        txt3.setColumns(20);
        txt3.setRows(5);
        jScrollPane1.setViewportView(txt3);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(30, 300, 580, 240);

        b3.setText("Ir a consejos generales");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(410, 150, 250, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt2ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
      
        
        try
          {
          
           if  (txt1.getText().isEmpty() || txt2.getText().isEmpty())
           {
         JOptionPane.showMessageDialog(null,"No has ingresado datos o te falta un campo","error",JOptionPane.ERROR_MESSAGE);
           
           }
         
    int pus= Integer.parseInt(txt1.getText());
    int pui= Integer.parseInt(txt2.getText());
    int pas1=120;
    int pai1=80;
    int pas2=90;
    int pai2=60;
    int pasas=140;
    int pasai=90;
    int pasdms=300;
    int pasdmi=300;
    int pasdms1=20;
    int pasdmi2=20;
        
    
       
          if (pus<=pas1 && pui<=pai1 && pus>=pas2 && pui>=pai2 )

        {
    txt3.setText(" TU PRESION ESTA ENTRE LOS RANGOS ADECUADOS Y NORMALES.");
    txt3.setEnabled(false);
    txt3.setBackground(Color.cyan);
    txt3.setForeground(Color.red);
    txt3.setDisabledTextColor(Color.BLACK);
    txt3.setBorder(new LineBorder(Color.GREEN));

        }
          else
                if (pus>pas1 && pui>pai1 && pus<pasas && pui<pasai )

        {
            txt3.setText("\n" + "\n Usted sufre de prehipertension , es propenso a padecer"
                    + "\n hipertension arterial, consulte a su médico.");
     txt3.setEnabled(false);
    txt3.setBackground(Color.cyan);
    txt3.setForeground(Color.red);
    txt3.setDisabledTextColor(Color.BLACK);
    txt3.setBorder(new LineBorder(Color.GREEN));

        }
                else 
      if (pus>=pasas && pui>=pasai && pus<pasdms && pui<pasdmi)
                    {
    txt3.setText("\n" + "\n Usted padece de Hipertension arterial,"
     +"\n debe de estar en tratamiento para este padecimiento."
     +"\n Si esta no es su situacion se le recomienda ir"
     + "\n al medico lo m?s antes posible.");
    txt3.setEnabled(false);
    txt3.setBackground(Color.cyan);
    txt3.setForeground(Color.red);
    txt3.setDisabledTextColor(Color.BLACK);
    txt3.setBorder(new LineBorder(Color.GREEN));
                        
                    }
           else 
                    if (pus<pas2 && pui<pai2 && pus>=pasdms1 && pus>=pasdmi2  )
                    {
                        txt3.setText(" Usted tiene Hipotension , presion arterial baja sucede"
                                + "\n cuando la presion arterial es mucho mas baja de lo normal. "
                                + "\n Esto significa que el corazon, el cerebro y "
                                + "\n otras partes del cuerpo no reciben suficiente sangre.");
    txt3.setEnabled(false);
    txt3.setBackground(Color.cyan);
    txt3.setForeground(Color.red);
    txt3.setDisabledTextColor(Color.BLACK);
    txt3.setBorder(new LineBorder(Color.GREEN));
                    }
       else
                     if(pus<pasdms1 && pus<pasdmi2  )
                        {
    txt3.setText("Esto no puede ser posible");
    txt3.setEnabled(false);
    txt3.setBackground(Color.cyan);
    txt3.setForeground(Color.red);
    txt3.setDisabledTextColor(Color.BLACK);
    txt3.setBorder(new LineBorder(Color.GREEN));
                        }
        else
                          if(pus>=pasdms && pui>=pasdmi )
                        {
    txt3.setText("Esto no puede ser posible");
    txt3.setEnabled(false);
    txt3.setBackground(Color.cyan);
    txt3.setForeground(Color.red);
    txt3.setDisabledTextColor(Color.BLACK);
    txt3.setBorder(new LineBorder(Color.GREEN));
                        }
        
                  
                    
                              } 
             catch(IllegalArgumentException e) {

             }
                        
                      
                     
          
        

    }//GEN-LAST:event_b2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        try{
        if  (txt1.getText().isEmpty() && txt2.getText().isEmpty())
           {
         JOptionPane.showMessageDialog(null,"No has ingresado datos","error",JOptionPane.ERROR_MESSAGE);
           }
          
        
       txt1.setText("");
       txt2.setText("");
       txt3.setText("");
           
        } 
             catch(IllegalArgumentException e) {

             }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
pruebadeglucosa1 pg= new pruebadeglucosa1();
pg.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
        this.dispose();
        proyectito.ConGe cg=new proyectito.ConGe ();
        cg.setVisible(true);
    }//GEN-LAST:event_b3ActionPerformed

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
       char  c=evt.getKeyChar();
       if (Character.isLetter(c)) {
           evt.consume();
           JOptionPane.showMessageDialog(null,"SOLO SE PUEDEN INGRESAR NUMEROS");
           }    
    }//GEN-LAST:event_txt1KeyTyped

    private void txt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyTyped
       char  c=evt.getKeyChar();
       if (Character.isLetter(c)) {
           evt.consume();
           JOptionPane.showMessageDialog(null,"SOLO SE PUEDEN INGRESAR NUMEROS");
           }    
    }//GEN-LAST:event_txt2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(presionart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(presionart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(presionart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(presionart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new presionart().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextArea txt3;
    // End of variables declaration//GEN-END:variables
}
