/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package no1;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

/**
 *
 * @author katy
 */
public class pruebaglucosa2 extends javax.swing.JFrame {

    /**
     * Creates new form pruebaglucosa2
     */
    public pruebaglucosa2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txt1 = new javax.swing.JTextField();
        b1 = new javax.swing.JToggleButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt2 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("PRUEBA DE GLUCOSA");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(203, 0, 477, 72);

        jLabel2.setText("Introduce tus niveles de glucosa");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 110, 190, 60);

        txt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt1ActionPerformed(evt);
            }
        });
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });
        getContentPane().add(txt1);
        txt1.setBounds(310, 100, 210, 60);

        b1.setText("Registrar");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(50, 200, 240, 30);

        txt2.setColumns(20);
        txt2.setRows(5);
        jScrollPane1.setViewportView(txt2);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 330, 630, 180);

        jButton1.setText("Limpiar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 200, 250, 30);

        jButton2.setText("Checa tu presion arterial");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(50, 250, 240, 40);

        b2.setText("Ir a consejos generales");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2);
        b2.setBounds(320, 250, 250, 40);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        try{           
      
           if(txt1.getText().isEmpty()) 
      {
             
         JOptionPane.showMessageDialog(null,"No has ingresado valores","error",JOptionPane.ERROR_MESSAGE);
           
     
      }
           
        int gu=Integer.parseInt(txt1.getText());//los niveles que ingresa el usuariop C:
        int gc=140;//rangos tope  de glucosa
        int ga=300;//rango alto 
        int gm2=70;//rangos muy bajos de glucosa
        int gm=1000;//rango super alto PRACTICAMENTE YA EN EL HOSPITAL O PAL VELATORIO 
     
        if ( gu<=gc && gu>=gm2 )

        {
            txt2.setText("Tus niveles de glucosa son perfectos.");
    txt2.setEnabled(false);
    txt2.setBackground(Color.cyan);
    txt2.setForeground(Color.red);
    txt2.setDisabledTextColor(Color.BLACK);
    txt2.setBorder(new LineBorder(Color.GREEN));
        }

        else

        if (gu>=gc && gu<ga)
        {
            txt2.setText("\n" + " \n Es necesario que consultes a tu medico, tus niveles no son los adecuados"
                + "\n" + "\n estas en riesgo de padecer diabetes.");
    txt2.setEnabled(false);
    txt2.setBackground(Color.cyan);
    txt2.setForeground(Color.red);
    txt2.setDisabledTextColor(Color.BLACK);
    txt2.setBorder(new LineBorder(Color.GREEN));
        }
        else
        if(gu>=ga && gu<=gm )
        {
            txt2.setText("\n Lamentamos decirte que padeces diabetes,"
                    + "\n si esto no lo sabias es urgente que consultes a un medico.");
    txt2.setEnabled(false);
    txt2.setBackground(Color.cyan);
    txt2.setForeground(Color.red);
    txt2.setDisabledTextColor(Color.BLACK);
    txt2.setBorder(new LineBorder(Color.GREEN));
        }
        else
            if (gu>gm)
        {
    txt2.setText("No puede ser posible esos niveles.");
    txt2.setEnabled(false);
    txt2.setBackground(Color.cyan);
    txt2.setForeground(Color.red);
    txt2.setDisabledTextColor(Color.BLACK);
    txt2.setBorder(new LineBorder(Color.GREEN));
        }
         else
            if (gu<gm2)
        {
    txt2.setText("No puede ser posible esos niveles.");
    txt2.setEnabled(false);
    txt2.setBackground(Color.cyan);
    txt2.setForeground(Color.red);
    txt2.setDisabledTextColor(Color.BLACK);
    txt2.setBorder(new LineBorder(Color.GREEN));
        }
           
     
             } 
             catch(IllegalArgumentException e) {

             }
         
        
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
      try{           
      
           if(txt1.getText().isEmpty()) 
      {
             
         JOptionPane.showMessageDialog(null,"No has ingresado valores","error",JOptionPane.ERROR_MESSAGE);
           
     
      }
        
      txt2.setText("");
      txt1.setText("");
      
     
             } 
             catch(IllegalArgumentException e) {

             }
      

            
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
        presionart pa=new  presionart  ();
        pa.setVisible(true);        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        this.dispose();
        proyectito.ConGe cg=new proyectito.ConGe ();
        cg.setVisible(true);
    }//GEN-LAST:event_b2ActionPerformed

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
       char  c=evt.getKeyChar();
       if (Character.isLetter(c)) {
           evt.consume();
           JOptionPane.showMessageDialog(null,"SOLO SE PUEDEN INGRESAR NUMEROS");
           }    
       
    }//GEN-LAST:event_txt1KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pruebaglucosa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pruebaglucosa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pruebaglucosa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pruebaglucosa2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new pruebaglucosa2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextArea txt2;
    // End of variables declaration//GEN-END:variables
}
