/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectito;


import java.awt.Desktop;
import java.net.URI;
import javax.swing.JOptionPane;



/**
 *
 * @author Lab314
 */
public class ConGe extends javax.swing.JFrame {

    /**
     * Creates new form ConGe
     */
    public ConGe() {
        initComponents();
 
        grupo1.add(rb1);
        grupo1.add(rb2);
        grupo1.add(rb3);
        grupo1.add(rb4);
        
      int a;
        a = 5;
  
    }                                   
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        rb1 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        rb4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        b3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(610, 600));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial Black", 0, 12)); // NOI18N
        jLabel1.setText("Como controlar la diabetes todos los dias.");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 10, 340, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/s2.png"))); // NOI18N
        jButton1.setText("SALIR");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/s1.png"))); // NOI18N
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/s3.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(420, 430, 140, 70);

        rb1.setBackground(new java.awt.Color(102, 204, 255));
        rb1.setText("1.- Siga un plan de comidas.");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1);
        rb1.setBounds(0, 90, 230, 40);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 90, 250, 50);

        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(330, 180, 230, 70);

        rb2.setBackground(new java.awt.Color(102, 204, 255));
        rb2.setText("2.- Realice actividad fisica con regularidad.");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2);
        rb2.setBounds(0, 180, 300, 40);

        rb3.setBackground(new java.awt.Color(102, 204, 255));
        rb3.setText("3.- Tome los medicamentos que su Doctor le receta.");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });
        getContentPane().add(rb3);
        rb3.setBounds(0, 280, 350, 30);

        rb4.setBackground(new java.awt.Color(102, 204, 255));
        rb4.setText("4.- Midase el nivel de glucosa en la sangre.");
        getContentPane().add(rb4);
        rb4.setBounds(0, 370, 310, 30);

        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel4);
        jLabel4.setBounds(360, 260, 180, 60);

        jButton2.setText("Ir");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(440, 380, 60, 19);

        jLabel5.setText("Escoge la opcion que te interese.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(180, 30, 210, 30);

        jLabel6.setText("Te recomendamos sitios web, donde puedes ver mas a detalle la informacion.");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(90, 50, 460, 40);

        b3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        b3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/r2.png"))); // NOI18N
        b3.setText("Regresar a 'Tipos'");
        b3.setBorder(null);
        b3.setBorderPainted(false);
        b3.setContentAreaFilled(false);
        b3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        b3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/r1.png"))); // NOI18N
        b3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/r3.png"))); // NOI18N
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3);
        b3.setBounds(10, 430, 240, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/blue.jpg"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-10, -320, 660, 1210);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
JOptionPane.showMessageDialog(null, "Si te interesa saber mas sobre un plan de comidas," + "\n Da clic en el link deseado." + "\n Para que vayas directamente al Sitio web.");
        jLabel2.setText("<html><a href=>http://www.manyar.com.mx/web/planes.php </a></html>");   

// TODO add your handling code here:
    }//GEN-LAST:event_rb1ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
try {
if (Desktop.isDesktopSupported()) {
Desktop desktop = Desktop.getDesktop();
if (desktop.isSupported(Desktop.Action.BROWSE)) {
desktop.browse(new URI("http://www.manyar.com.mx/web/planes.php"));
}
}
} 

catch (Exception e) { 
    e.printStackTrace();
}      
    }//GEN-LAST:event_jLabel2MouseClicked

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
JOptionPane.showMessageDialog(null, "Si te interesa saber mas sobre ejercicios fisicos" + "\n Da clic en el link deseado." + "\n Para que vayas directamente al Sitio web.");
        jLabel3.setText("<html><a href=>http://www.diabetes.org/es/alimentos-y-actividad-fisica/condicion-fisica/tipos-de-ejercicio/?referrer=https://www.google.com.mx/</a></html>"); 
    }//GEN-LAST:event_rb2ActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
try {
if (Desktop.isDesktopSupported()) {
Desktop desktop = Desktop.getDesktop();
if (desktop.isSupported(Desktop.Action.BROWSE)) {
desktop.browse(new URI("http://www.diabetes.org/es/alimentos-y-actividad-fisica/condicion-fisica/tipos-de-ejercicio/?referrer=https://www.google.com.mx/"));
}
}
} catch (Exception e) {
e.printStackTrace();

}         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel3MouseClicked

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
JOptionPane.showMessageDialog(null, "Si te interesa saber mas sobre atencion medica," + "\n Da clic en el link que acaba de aparecer." + "\n Para que vayas directamente al Sitio web.");
        jLabel4.setText("<html><a href=>www.clinicadediabetes.com.mx/‎ </a></html>");   
        // TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
try {
if (Desktop.isDesktopSupported()) {
Desktop desktop = Desktop.getDesktop();
if (desktop.isSupported(Desktop.Action.BROWSE)) {
desktop.browse(new URI("http://www.clinicadediabetes.com.mx/"));
}
}
} catch (Exception e) {
e.printStackTrace();

}         // TODO add your handling code here:
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 this.dispose();
        tabla2 tab=new tabla2 ();
        tab.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
         this.dispose();
       SI si=new SI();
        si.setVisible(true);
    }//GEN-LAST:event_b3ActionPerformed

    
   
  
    public static void main(String args[]) {
      
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new ConGe().setVisible(true);
            }
        });
    
 
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b3;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JRadioButton rb4;
    // End of variables declaration//GEN-END:variables
}
