/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectito;

import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.border.LineBorder;

import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;


/**
 *
 * @author Lab314
 */
public class Gestacional extends javax.swing.JFrame {
public Clip clip;
   public String ruta= "/proyectito/";
    /**
     * Creates new form Gestacional
     */
    public Gestacional() {
        initComponents();
       
        btn1.setEnabled(false);
     txt1.setEnabled(false);
    txt1.setBackground(Color.blue);
    txt1.setForeground(Color.red);
    txt1.setDisabledTextColor(Color.BLACK);
    txt1.setBorder(new LineBorder(Color.GREEN));
    
    }
public void sonido(String archivo) {
try {
clip=AudioSystem.getClip();
clip.open(AudioSystem.getAudioInputStream(getClass().getResourceAsStream(ruta + archivo + ".wav")));
clip.start();
}

catch
        (Exception e){}
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txt = new javax.swing.JTextField();
        btn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();
        btn1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(500, 530));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Cuantas semanas tienes de embarazo?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 20, 230, 40);

        txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtActionPerformed(evt);
            }
        });
        getContentPane().add(txt);
        txt.setBounds(320, 20, 94, 41);

        btn.setText("Consultar");
        btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActionPerformed(evt);
            }
        });
        getContentPane().add(btn);
        btn.setBounds(70, 70, 140, 23);

        txt1.setColumns(20);
        txt1.setRows(5);
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txt1KeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txt1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(70, 100, 326, 236);

        btn1.setText("Consultar de Nuevo");
        btn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1ActionPerformed(evt);
            }
        });
        getContentPane().add(btn1);
        btn1.setBounds(240, 70, 150, 23);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/i2.png"))); // NOI18N
        jButton3.setText("Ir a Consejos Generales");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/i1.png"))); // NOI18N
        jButton3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/i3.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(110, 350, 250, 70);

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
        });
        getContentPane().add(jLabel2);
        jLabel2.setBounds(44, 14, 390, 410);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActionPerformed
      
        btn1.setEnabled(true);
      try
         {
             
              
       if(txt.getText().isEmpty()) 
      {
             
         JOptionPane.showMessageDialog(null,"No has ingresado valores","error",JOptionPane.ERROR_MESSAGE);
           
     
      }
        
       
       
           int resp= Integer.parseInt(txt.getText());
           int n1=24;
           int n2=40;
   
         
           
           
           if(resp==n1)
         {
           txt1.setText("\n" + " Por lo general los síntimas se" + "\n" + " presentan a partir de esta semana," + "\n"+ " te recomendamos llevar un chequeo" + "\n"+ " a partir de ahora.");
            }
      else 
      if  (resp>n1){
    txt1.setText("\n" + " Si has presentado algunos de estos síntomas: " + "\n" + "1.- Vision Borrosa" +"\n" + "2.- Fatiga " + "\n" +
            "3.- Sed y polidipsia, la polidipsia es" + "\n" + " el gran consumo de agua"+ "\n"+ "4.- Poliuria" +"\n" + "5.- Nauseas y vomitos"+ "\n" + "6.- Perdida de peso" +
            "\n" +" Te recomendamos llevar un control de tu embarazo," + 
      "\n" + " ya que estos sintomas se presentan" + "\n" +" en la semana en la que estas o un poco antes.");
    }
       else
        if (resp<n1)
        {
       txt1.setText("\n" + " NO se puede saber con certeza si usted" + "\n" + " padece Diabetes Gestacional, Ya que los" + "\n" + " síntomas se presentan a partir" + "\n de la semana 24 de embarazo.");
        }
       else
        if (resp>=n2)
    {
         txt1.setText("\n " + "\n Esto no puede ser posible.");
    }
        
    
              } 
             catch(IllegalArgumentException e) {

             }
         
       
       
    }//GEN-LAST:event_btnActionPerformed

    private void txt1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt1KeyPressed

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
      
    }//GEN-LAST:event_txt1KeyTyped

    private void btn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1ActionPerformed
       
        
        btn1.setEnabled(true);
        
        try
         {
             
              
       if(txt.getText().isEmpty()) 
      {
             
         JOptionPane.showMessageDialog(null,"No has ingresado valores","error",JOptionPane.ERROR_MESSAGE);
           
     
      }
        
     
        
        txt.setText("");
         txt1.setText("");// TODO add your handling code here:
            
              } 
             catch(IllegalArgumentException e) {

             }
         
    }//GEN-LAST:event_btn1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       this.dispose();
       ConGe cg=new ConGe ();
       cg.setVisible(true);            // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtActionPerformed
 
    }//GEN-LAST:event_txtActionPerformed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
  sonido("kam");      // TODO add your handling code here:
    }//GEN-LAST:event_jLabel2MouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestacional.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Gestacional().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn;
    private javax.swing.JButton btn1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txt;
    private javax.swing.JTextArea txt1;
    // End of variables declaration//GEN-END:variables
}
