/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectito;

import java.awt.Color;
import javax.swing.border.LineBorder;

/**
 *
 * @author Lab314
 */
public class P2 extends javax.swing.JFrame {

    /**
     * Creates new form P2
     */
    public P2() {
       
         initComponents();
        grupo1.add(rb1);
        grupo1.add(rb2);
        grupo1.add(rb3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();
        b1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jLabel1.setText("Pregunta 2 de 8");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(30, 0, 160, 50);

        jLabel2.setText("Mis valores de glucosa se encuentran dentro del rango que mi medico recomienda.");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 500, 50);

        rb1.setText("Nunca");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1);
        rb1.setBounds(30, 160, 110, 23);

        rb2.setText("A veces");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2);
        rb2.setBounds(30, 190, 140, 23);

        rb3.setText("Siempre");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });
        getContentPane().add(rb3);
        rb3.setBounds(30, 220, 140, 23);

        txt1.setColumns(20);
        txt1.setRows(5);
        jScrollPane1.setViewportView(txt1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(170, 90, 390, 270);

        b1.setText("Siguiente");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(320, 380, 110, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
    this.txt1.setText("\n"+ "  NUNCA"+"\n" +"\n Haga una cita con su medico. Puede ser hora"
                                           +"\n de ajustar su tratamiento, para tratar de poner " 
                                           + "\n su glucosa bajo un mejor control." 
                                           + "\n Al mantener su glucosa en su rango usted puede "
                                           +"\n ayudar a reducir su riesgo de complicaciones "
                                           +"\n serias relacionadas con la diabetes.");
                                       
   
    txt1.setEnabled(false);
    txt1.setBackground(Color.yellow);
    txt1.setForeground(Color.red);
    txt1.setDisabledTextColor(Color.BLACK);
    txt1.setBorder(new LineBorder(Color.GREEN));
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
  this.txt1.setText("\n" + "  A VECES" + "\n" 
          + "\n Si no cumple sistematicamente sus metas de glucosa,"
          + "\n a pesar de todos sus esfuerzos, puede ser hora" 
          + "\n de ver a su medico.  El tal vez quiera cambiar"
          + "\n su tratamiento, para ayudarlo a alcanzar sus" 
          + "\n metas de glucosa."
          + "\n Si esta teniendo dificultad para seguir su plan de ," 
          + "\n tratamiento hable con su medico o asesor en diabetes.");
    txt1.setEnabled(false);
    txt1.setBackground(Color.yellow);
    txt1.setForeground(Color.red);
    txt1.setDisabledTextColor(Color.BLACK);
    txt1.setBorder(new LineBorder(Color.GREEN));
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
       this.txt1.setText("\n" + "  SIEMPRE" + "\n" 
               +  "\n Al mantener sus niveles de glucosa en su zona objetivo,"
          +"\n"+" puede ayudar a reducir su riesgo de complicaciones" 
               + "\n de diabetes. Si aun no lo esta haciendo," 
               +"\n Lleve un registro de sus lecturas de glucosa"
               +"\n" +" junto con lo que come y su nivel de actividad física "
               +"\n" +" Este registro puede ayudarle a ver " 
               + "\n que esta afectando sus lecturas de glucosa.");
    txt1.setEnabled(false);
     txt1.setBackground(Color.yellow);
    txt1.setForeground(Color.red);
    txt1.setDisabledTextColor(Color.BLACK);
    txt1.setBorder(new LineBorder(Color.GREEN));
    }//GEN-LAST:event_rb3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        this.dispose();
        P3 p3=new P3 ();
        p3.setVisible(true);
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new P2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JTextArea txt1;
    // End of variables declaration//GEN-END:variables
}
