/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectito;

import java.awt.Color;
import javax.swing.border.LineBorder;

/**
 *
 * @author Lab314
 */
public class P5 extends javax.swing.JFrame {

    /**
     * Creates new form P5
     */
    public P5() {
        initComponents();
        grupo1.add(rb1);
        grupo1.add(rb2);
        grupo1.add(rb3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(700, 600));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel4.setText("Pregunta 5 de 8");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 10, 320, 50);

        jLabel5.setText("Yo sigo las recomendaciones de mi medico con respecto a un plan de alimentacion sana.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 60, 510, 50);

        rb1.setText("Nunca");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1);
        rb1.setBounds(60, 130, 110, 23);

        rb2.setText("A veces");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2);
        rb2.setBounds(60, 160, 110, 23);

        rb3.setText("Siempre");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });
        getContentPane().add(rb3);
        rb3.setBounds(60, 190, 130, 23);

        txt1.setColumns(20);
        txt1.setRows(5);
        jScrollPane1.setViewportView(txt1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(200, 110, 400, 250);

        jButton1.setText("Siguiente");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(340, 380, 130, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
       this.txt1.setText("\n" +" NUNCA"+"\n"+
               "\n"+" Cambiar la manera de comer puede ser dificil, pero es una " +
               "\n parte muy importante del control de su glucosa, incluso si"+
               "\n toma medicamentos para la diabetes."
             + "\n Si no sabe cuanto come o que debe comer o si se le dificulta"
             + "\n seguir un plan de alimentacion, hable con su medico. El puede"
             + "\n"+" enviarlo a un dietista o experto en nutricion que puede "
             + "\n" +"ayudarlo a desarrollar un plan quev incluya los alimentos que disfruta.");
txt1.setEnabled(false);
   txt1.setBackground(Color.pink);
    txt1.setForeground(Color.red);
    txt1.setDisabledTextColor(Color.BLACK);
    txt1.setBorder(new LineBorder(Color.CYAN));
 
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
   this.txt1.setText("\n" + " A VECES" + "\n" 
           + "\n La alimentacion sana es una parte importante del manejo de la "+ 
             "\n diabetes, ya sea que su medico desee o no que usted baje de peso. "
           + "\n Si se desea ayudar con una alimentacion sana, hable con su medico , "
           + "\n asesor en diabetes, dietista o experto en nutricion. El puede "
          + "\n  ayudarlo a crear un plan de alimentacion que incluya los "
           + "\n alimentos que le gustan y que pueden ayudarle a seguir el plan.");
txt1.setEnabled(false);
      txt1.setBackground(Color.pink);
    txt1.setForeground(Color.red);
    txt1.setDisabledTextColor(Color.BLACK);
    txt1.setBorder(new LineBorder(Color.CYAN));       // TODO add your handling code here:
    }//GEN-LAST:event_rb2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
this.dispose();
        P6 p6=new P6 ();
        p6.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
this.txt1.setText("\n" + " SIEMPRE"+ "\n"+
        "\n Comer sano es clave para manejar la diabetes tipo 2."
        + "\n No existe una dieta para diabetes."
        + "\n Sin embargo, a veces usted puede tener problemas" + 
        "\n para seguir su plan. Si esto sucede,"
        + "\n lo importante es superar su problema y reactivar el plan.");
    txt1.setEnabled(false);
      txt1.setBackground(Color.pink);
    txt1.setForeground(Color.red);
    txt1.setDisabledTextColor(Color.BLACK);
    txt1.setBorder(new LineBorder(Color.CYAN));         // TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P5.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new P5().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JTextArea txt1;
    // End of variables declaration//GEN-END:variables
}
