/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectito;

import java.awt.Color;
import javax.swing.border.LineBorder;

/**
 *
 * @author Lab314
 */
public class P7 extends javax.swing.JFrame {

    /**
     * Creates new form P7
     */
    public P7() {
        initComponents();
        
         grupo1.add(rb2);
         grupo1.add(rb1);
         grupo1.add(rb3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupo1 = new javax.swing.ButtonGroup();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        rb1 = new javax.swing.JRadioButton();
        rb2 = new javax.swing.JRadioButton();
        rb3 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt1 = new javax.swing.JTextArea();
        b1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(0, 0));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(700, 600));
        getContentPane().setLayout(null);

        jLabel5.setText("Pregunta 7 de 8");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(20, 0, 320, 50);

        jLabel3.setText("Yo administro mis medicamentos para la diabetes como me los prescribio el médico");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 40, 650, 50);

        rb1.setText("Si");
        rb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb1ActionPerformed(evt);
            }
        });
        getContentPane().add(rb1);
        rb1.setBounds(40, 130, 90, 23);

        rb2.setText("No");
        rb2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb2ActionPerformed(evt);
            }
        });
        getContentPane().add(rb2);
        rb2.setBounds(40, 160, 93, 23);

        rb3.setText("No aplica");
        rb3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rb3ActionPerformed(evt);
            }
        });
        getContentPane().add(rb3);
        rb3.setBounds(40, 190, 100, 23);

        txt1.setColumns(20);
        txt1.setRows(5);
        jScrollPane1.setViewportView(txt1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 90, 420, 230);

        b1.setText("Siguiente");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1);
        b1.setBounds(310, 340, 140, 30);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void rb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb1ActionPerformed
        this.txt1.setText("\n" + " SI?" + "\n"
                + "\n Muchas personas con diabetes tipo 2 necesitan uno o mas"
                + "\n medicamentos para controlar su glucosa. Pruebe su glucosa "
                + "\n con regularidad y mantenga un registro de sus resultados. "
                + "\n Esto le ayudara a usted y a su medico a ver qué tan bien"
                + "\n esta funcionando su tratamiento actual."
                + "\n Siga tomando su medicamento como se lo receta el medico,"
                + "\n incluso cuando esté en su meta de glucosa.");
    txt1.setEnabled(false);
    txt1.setBackground(Color.magenta);
    txt1.setForeground(Color.BLACK);
    txt1.setDisabledTextColor(Color.BLACK);
    txt1.setBorder(new LineBorder(Color.BLUE)); 
    }//GEN-LAST:event_rb1ActionPerformed

    private void rb2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb2ActionPerformed
        this.txt1.setText("\n" + "  NO?" + "\n"
                + "\n Para muchas personas con diabetes tipo 2,"
                + "\n el medicamento es clave para controlar su glucosa."
                + "\n Si usted tiene efectos colaterales que dificulten continuar su tratamiento,"
                + "\n hable con su medico."
                + "\n el puede ajustar su dosis o cambiar su medicamento.");
    txt1.setEnabled(false);
  txt1.setBackground(Color.magenta);
    txt1.setForeground(Color.BLACK);
    txt1.setDisabledTextColor(Color.BLACK);
    txt1.setBorder(new LineBorder(Color.BLUE)); 
    }//GEN-LAST:event_rb2ActionPerformed

    private void rb3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rb3ActionPerformed
   this.txt1.setText("\n " + " NO APLICA" + "\n"
           + "\n Su diabetes puede cambiar con el tiempo, es por eso que "
           + "\n es importante que su médico cheque sus valores con regularidad."
           + "\n Esto le permite hablar de como esta funcionando su  plan de tratamiento"
           + "\n y si es hora de considerar agregar medicamentos a ese plan.");
    txt1.setEnabled(false);
   txt1.setBackground(Color.magenta);
    txt1.setForeground(Color.BLACK);
    txt1.setDisabledTextColor(Color.BLACK);
    txt1.setBorder(new LineBorder(Color.BLUE));      // TODO add your handling code here:
    }//GEN-LAST:event_rb3ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        this.dispose();
        P8 p8=new P8 ();
        p8.setVisible(true);
    }//GEN-LAST:event_b1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(P7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(P7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(P7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(P7.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new P7().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.ButtonGroup grupo1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JRadioButton rb1;
    private javax.swing.JRadioButton rb2;
    private javax.swing.JRadioButton rb3;
    private javax.swing.JTextArea txt1;
    // End of variables declaration//GEN-END:variables
}
