/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectito;

/**
 *
 * @author Lab314
 */
public class Principal extends javax.swing.JFrame {
    private Object SubstanceLookAndFeel;

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnno = new javax.swing.JButton();
        btnsi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(0, 0));
        setPreferredSize(new java.awt.Dimension(610, 360));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setText("\"Salvarte o Controlarla\"");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(90, 150, 440, 40);

        jLabel3.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 204));
        jLabel3.setText("Padeces Diabetes?");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(190, 190, 220, 50);

        btnno.setFont(new java.awt.Font("Yu Mincho", 0, 24)); // NOI18N
        btnno.setForeground(new java.awt.Color(51, 51, 255));
        btnno.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/n2.png"))); // NOI18N
        btnno.setText("NO");
        btnno.setBorder(null);
        btnno.setBorderPainted(false);
        btnno.setContentAreaFilled(false);
        btnno.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnno.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/n1.png"))); // NOI18N
        btnno.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/n3.png"))); // NOI18N
        btnno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnoActionPerformed(evt);
            }
        });
        getContentPane().add(btnno);
        btnno.setBounds(410, 240, 140, 70);

        btnsi.setFont(new java.awt.Font("Yu Mincho", 0, 24)); // NOI18N
        btnsi.setForeground(new java.awt.Color(0, 0, 255));
        btnsi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/2.jpg"))); // NOI18N
        btnsi.setText("SI");
        btnsi.setBorder(null);
        btnsi.setBorderPainted(false);
        btnsi.setContentAreaFilled(false);
        btnsi.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsi.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/3.jpg"))); // NOI18N
        btnsi.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/1.jpg"))); // NOI18N
        btnsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsiActionPerformed(evt);
            }
        });
        getContentPane().add(btnsi);
        btnsi.setBounds(40, 240, 140, 71);

        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectito/d1.jpg"))); // NOI18N
        jLabel4.setMaximumSize(new java.awt.Dimension(0, 0));
        jLabel4.setMinimumSize(new java.awt.Dimension(0, 0));
        jLabel4.setName(""); // NOI18N
        jLabel4.setPreferredSize(new java.awt.Dimension(610, 800));
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 690, 330);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsiActionPerformed
       this.dispose();
       SI si=new SI ();
        si.setVisible(true);      
    }//GEN-LAST:event_btnsiActionPerformed

    private void btnnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnoActionPerformed
        this.dispose();
        no1.no no=new no1.no ();
        no.setVisible(true);
    }//GEN-LAST:event_btnnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnno;
    private javax.swing.JButton btnsi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JList jList1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
